logging:
  level:
    org.springframework: INFO
    com.nttdata: DEBUG
    org.springframework.jdbc.core.JdbcTemplate: DEBUG
spring:
  jackson:
    serialization:
      indent-output: true
      write-dates-as-timestamps: false
    default-property-inclusion: non_null
    date-format: yyyy-MM-dd'T'HH:mm:ssX
  datasource:
    url: jdbc:oracle:thin:@//cgn-thorin-01.de.softlab.net:1521/salcos
    username: salcos
    password: ora123
    driverClassName: oracle.jdbc.OracleDriver
  jpa:
    show-sql: true
  main:
    banner-mode: "off"
  application:
    name: '@project.name@'
target: http://localhost:9999/catalogManagement/v2
info:
  app:
    name: '@project.name@'
    description: '@project.description@'
    version: '@project.version@'
    encoding: '@project.build.sourceEncoding@'
    java:
      version: '@java.version@'
